/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutSbcRouteImport } from './routes/about-sbc'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BookFreeAuditRouteImport } from './routes/book-free-audit'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ConsultingFirmsInAhmedabadRouteImport } from './routes/consulting-firms-in-ahmedabad'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as Gap360RouteImport } from './routes/gap360'
import { Route as InstitutionBuildingSkillDevelopmentRouteImport } from './routes/institution-building-skill-development'
import { Route as MsmeConsultingRouteImport } from './routes/msme-consulting'
import { Route as OurApproachRouteImport } from './routes/our-approach'
import { Route as PolicyAdvisoryRouteImport } from './routes/policy-advisory'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as StrategicResearchFeasibilityRouteImport } from './routes/strategic-research-feasibility'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutSbcRoute = AboutSbcRouteImport.update({
  id: '/about-sbc',
  path: '/about-sbc',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BookFreeAuditRoute = BookFreeAuditRouteImport.update({
  id: '/book-free-audit',
  path: '/book-free-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultingFirmsInAhmedabadRoute =
  ConsultingFirmsInAhmedabadRouteImport.update({
    id: '/consulting-firms-in-ahmedabad',
    path: '/consulting-firms-in-ahmedabad',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const Gap360Route = Gap360RouteImport.update({
  id: '/gap360',
  path: '/gap360',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionBuildingSkillDevelopmentRoute =
  InstitutionBuildingSkillDevelopmentRouteImport.update({
    id: '/institution-building-skill-development',
    path: '/institution-building-skill-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const MsmeConsultingRoute = MsmeConsultingRouteImport.update({
  id: '/msme-consulting',
  path: '/msme-consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const OurApproachRoute = OurApproachRouteImport.update({
  id: '/our-approach',
  path: '/our-approach',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyAdvisoryRoute = PolicyAdvisoryRouteImport.update({
  id: '/policy-advisory',
  path: '/policy-advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategicResearchFeasibilityRoute =
  StrategicResearchFeasibilityRouteImport.update({
    id: '/strategic-research-feasibility',
    path: '/strategic-research-feasibility',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CaseStudiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-sbc': typeof AboutSbcRoute
  '/blog': typeof BlogRouteWithChildren
  '/book-free-audit': typeof BookFreeAuditRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/consulting-firms-in-ahmedabad': typeof ConsultingFirmsInAhmedabadRoute
  '/contact': typeof ContactRoute
  '/founder': typeof FounderRoute
  '/gap360': typeof Gap360Route
  '/institution-building-skill-development': typeof InstitutionBuildingSkillDevelopmentRoute
  '/msme-consulting': typeof MsmeConsultingRoute
  '/our-approach': typeof OurApproachRoute
  '/policy-advisory': typeof PolicyAdvisoryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/resources': typeof ResourcesRoute
  '/strategic-research-feasibility': typeof StrategicResearchFeasibilityRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-sbc': typeof AboutSbcRoute
  '/book-free-audit': typeof BookFreeAuditRoute
  '/consulting-firms-in-ahmedabad': typeof ConsultingFirmsInAhmedabadRoute
  '/contact': typeof ContactRoute
  '/founder': typeof FounderRoute
  '/gap360': typeof Gap360Route
  '/institution-building-skill-development': typeof InstitutionBuildingSkillDevelopmentRoute
  '/msme-consulting': typeof MsmeConsultingRoute
  '/our-approach': typeof OurApproachRoute
  '/policy-advisory': typeof PolicyAdvisoryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/resources': typeof ResourcesRoute
  '/strategic-research-feasibility': typeof StrategicResearchFeasibilityRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/case-studies': typeof CaseStudiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-sbc': typeof AboutSbcRoute
  '/blog': typeof BlogRouteWithChildren
  '/book-free-audit': typeof BookFreeAuditRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/consulting-firms-in-ahmedabad': typeof ConsultingFirmsInAhmedabadRoute
  '/contact': typeof ContactRoute
  '/founder': typeof FounderRoute
  '/gap360': typeof Gap360Route
  '/institution-building-skill-development': typeof InstitutionBuildingSkillDevelopmentRoute
  '/msme-consulting': typeof MsmeConsultingRoute
  '/our-approach': typeof OurApproachRoute
  '/policy-advisory': typeof PolicyAdvisoryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/resources': typeof ResourcesRoute
  '/strategic-research-feasibility': typeof StrategicResearchFeasibilityRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-sbc'
    | '/blog'
    | '/book-free-audit'
    | '/case-studies'
    | '/consulting-firms-in-ahmedabad'
    | '/contact'
    | '/founder'
    | '/gap360'
    | '/institution-building-skill-development'
    | '/msme-consulting'
    | '/our-approach'
    | '/policy-advisory'
    | '/privacy-policy'
    | '/resources'
    | '/strategic-research-feasibility'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/blog/'
    | '/case-studies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-sbc'
    | '/book-free-audit'
    | '/consulting-firms-in-ahmedabad'
    | '/contact'
    | '/founder'
    | '/gap360'
    | '/institution-building-skill-development'
    | '/msme-consulting'
    | '/our-approach'
    | '/policy-advisory'
    | '/privacy-policy'
    | '/resources'
    | '/strategic-research-feasibility'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/blog'
    | '/case-studies'
  id:
    | '__root__'
    | '/'
    | '/about-sbc'
    | '/blog'
    | '/book-free-audit'
    | '/case-studies'
    | '/consulting-firms-in-ahmedabad'
    | '/contact'
    | '/founder'
    | '/gap360'
    | '/institution-building-skill-development'
    | '/msme-consulting'
    | '/our-approach'
    | '/policy-advisory'
    | '/privacy-policy'
    | '/resources'
    | '/strategic-research-feasibility'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/blog/'
    | '/case-studies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutSbcRoute: typeof AboutSbcRoute
  BlogRoute: typeof BlogRouteWithChildren
  BookFreeAuditRoute: typeof BookFreeAuditRoute
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
  ConsultingFirmsInAhmedabadRoute: typeof ConsultingFirmsInAhmedabadRoute
  ContactRoute: typeof ContactRoute
  FounderRoute: typeof FounderRoute
  Gap360Route: typeof Gap360Route
  InstitutionBuildingSkillDevelopmentRoute: typeof InstitutionBuildingSkillDevelopmentRoute
  MsmeConsultingRoute: typeof MsmeConsultingRoute
  OurApproachRoute: typeof OurApproachRoute
  PolicyAdvisoryRoute: typeof PolicyAdvisoryRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResourcesRoute: typeof ResourcesRoute
  StrategicResearchFeasibilityRoute: typeof StrategicResearchFeasibilityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-sbc': {
      id: '/about-sbc'
      path: '/about-sbc'
      fullPath: '/about-sbc'
      preLoaderRoute: typeof AboutSbcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-free-audit': {
      id: '/book-free-audit'
      path: '/book-free-audit'
      fullPath: '/book-free-audit'
      preLoaderRoute: typeof BookFreeAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulting-firms-in-ahmedabad': {
      id: '/consulting-firms-in-ahmedabad'
      path: '/consulting-firms-in-ahmedabad'
      fullPath: '/consulting-firms-in-ahmedabad'
      preLoaderRoute: typeof ConsultingFirmsInAhmedabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gap360': {
      id: '/gap360'
      path: '/gap360'
      fullPath: '/gap360'
      preLoaderRoute: typeof Gap360RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institution-building-skill-development': {
      id: '/institution-building-skill-development'
      path: '/institution-building-skill-development'
      fullPath: '/institution-building-skill-development'
      preLoaderRoute: typeof InstitutionBuildingSkillDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/msme-consulting': {
      id: '/msme-consulting'
      path: '/msme-consulting'
      fullPath: '/msme-consulting'
      preLoaderRoute: typeof MsmeConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-approach': {
      id: '/our-approach'
      path: '/our-approach'
      fullPath: '/our-approach'
      preLoaderRoute: typeof OurApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy-advisory': {
      id: '/policy-advisory'
      path: '/policy-advisory'
      fullPath: '/policy-advisory'
      preLoaderRoute: typeof PolicyAdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategic-research-feasibility': {
      id: '/strategic-research-feasibility'
      path: '/strategic-research-feasibility'
      fullPath: '/strategic-research-feasibility'
      preLoaderRoute: typeof StrategicResearchFeasibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CaseStudiesRouteChildren {
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutSbcRoute: AboutSbcRoute,
  BlogRoute: BlogRouteWithChildren,
  BookFreeAuditRoute: BookFreeAuditRoute,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
  ConsultingFirmsInAhmedabadRoute: ConsultingFirmsInAhmedabadRoute,
  ContactRoute: ContactRoute,
  FounderRoute: FounderRoute,
  Gap360Route: Gap360Route,
  InstitutionBuildingSkillDevelopmentRoute:
    InstitutionBuildingSkillDevelopmentRoute,
  MsmeConsultingRoute: MsmeConsultingRoute,
  OurApproachRoute: OurApproachRoute,
  PolicyAdvisoryRoute: PolicyAdvisoryRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResourcesRoute: ResourcesRoute,
  StrategicResearchFeasibilityRoute: StrategicResearchFeasibilityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
